services:
    db:
        image: mysql:8
        container_name: mysql-container
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
            - ./mysql_data/dbschema.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - red_parking
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: parking-app:latest
        container_name: java-app-container
        ports: 
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/parking
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root
        depends_on:
            - db
        networks:
            - red_parking

volumes:
    db-data:
networks:
    red_parking: