-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 15:52:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `parking` ;

-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parking` DEFAULT CHARACTER SET utf8 ;
USE `parking` ;

-- -----------------------------------------------------
-- Table `parking`.`vehicles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`vehicles` ;

CREATE TABLE IF NOT EXISTS `parking`.`vehicles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `license_plate` VARCHAR(6) NOT NULL,
  `type` ENUM('MOTORCYCLE', 'CAR') NOT NULL,
  `fueltype` ENUM('ELECTRIC', 'HYBRID', 'GASOLINE') NOT NULL,
  `has_discount` TINYINT NULL,
  `is_deleted` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`prices` ;

CREATE TABLE IF NOT EXISTS `parking`.`prices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `price_per_hour` DECIMAL(14,2) NOT NULL,
  `type` ENUM('MOTORCYCLE', 'CAR') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`parking_slots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`parking_slots` ;

CREATE TABLE IF NOT EXISTS `parking`.`parking_slots` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `slot_number` VARCHAR(4) NOT NULL,
  `type` ENUM('MOTORCYCLE', 'CAR') NOT NULL,
  `update_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_available` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parking`.`parking_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parking`.`parking_records` ;

CREATE TABLE IF NOT EXISTS `parking`.`parking_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `has_discount` TINYINT NULL,
  `price_per_hour` DECIMAL(14,2) NOT NULL,
  `entry_time` DATETIME NOT NULL,
  `exit_time` DATETIME NULL,
  `update_at` DATETIME NOT NULL,
  `total_duration` BIGINT NULL,
  `amount_without_discount` DECIMAL(14,2) NULL,
  `total_amount` DECIMAL(14,2) NOT NULL,
  `is_parked` VARCHAR(45) NULL,
  `is_deleted` VARCHAR(45) NULL,
  `deleted_reason` ENUM('WRONG_PLATE', 'WRONG_VEHICLE_TYPE', 'DUPLICATE_ENTRY', 'OTHER') NULL,
  `vehicles_id` BIGINT NOT NULL,
  `parking_slots_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parking_records_vehicles_idx` (`vehicles_id` ASC) VISIBLE,
  INDEX `fk_parking_records_parkinglots1_idx` (`parking_slots_id` ASC) VISIBLE,
  CONSTRAINT `fk_parking_records_vehicles`
    FOREIGN KEY (`vehicles_id`)
    REFERENCES `parking`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parking_records_parkinglots1`
    FOREIGN KEY (`parking_slots_id`)
    REFERENCES `parking`.`parking_slots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `parking`.`prices`
-- -----------------------------------------------------
START TRANSACTION;
USE `parking`;
INSERT INTO `parking`.`prices` (`id`, `price_per_hour`, `type`) VALUES (DEFAULT, 62.00, 'MOTORCYCLE');
INSERT INTO `parking`.`prices` (`id`, `price_per_hour`, `type`) VALUES (DEFAULT, 120.00, 'CAR');

COMMIT;


-- -----------------------------------------------------
-- Data for table `parking`.`parking_slots`
-- -----------------------------------------------------
START TRANSACTION;
USE `parking`;
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'M1', 'MOTORCYCLE', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'M2', 'MOTORCYCLE', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'M3', 'MOTORCYCLE', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'M4', 'MOTORCYCLE', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'M5', 'MOTORCYCLE', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'M6', 'MOTORCYCLE', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'V1', 'CAR', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'V2', 'CAR', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'V3', 'CAR', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'V4', 'CAR', '', 1);
INSERT INTO `parking`.`parking_slots` (`id`, `slot_number`, `type`, `update_at`, `is_available`) VALUES (DEFAULT, 'V5', 'CAR', '', 1);

COMMIT;

